id: P005392
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG22039
  title: བོད་ཀྱི་ལ་གཞས།
  author: ''
  volumes:
    4dc54b6efef44a48b23ec9818b8df68e:
      image_group_id: I1KG22082
      title: ''
      volume_number: 1
      total_pages: 268
      base_file: v001.txt
