id: I440AB4AA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:57:18+00:00'
last_modified: '2022-06-08T02:45:36.044219+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22039
  title: བོད་ཀྱི་ལ་གཞས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    26CB:
      image_group_id: I1KG22082
      title: ''
      total_pages: 268
      order: 1
      base_file: 26CB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
